import type { ResumeDocument } from "./document"

/** Escapes text for LaTeX. Placeholders like [X%] stay visible so they're not forgotten. */
export function escapeLatex(text: string): string {
  return text
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/–/g, "--")
    .replace(/—/g, "---")
}

/** A single-column, ATS-friendly LaTeX resume (compiles on Overleaf with pdflatex). */
export function toLatex(doc: ResumeDocument): string {
  const e = escapeLatex
  const section = (title: string, body: string) => (body.trim() ? `\\section*{${title}}\n${body}\n` : "")
  const items = (bullets: string[]) =>
    bullets.length ? `\\begin{itemize}\n${bullets.map((b) => `  \\item ${e(b)}`).join("\n")}\n\\end{itemize}` : ""

  const education = doc.education
    .map((ed) => `\\textbf{${e(ed.institution)}} \\hfill ${e(ed.period)}\\\\\n${e(ed.detail)}`)
    .join("\n\n")
  const skills = doc.skills.map((s) => `\\textbf{${e(s.label)}:} ${e(s.items)}`).join("\\\\\n")
  const projects = doc.projects
    .map((p) => `\\textbf{${e(p.title)}}${p.tech ? ` | \\textit{${e(p.tech)}}` : ""}${p.link ? ` \\hfill ${e(p.link)}` : ""}\n${items(p.bullets)}`)
    .join("\n")
  const experience = doc.experience
    .map((x) => `\\textbf{${e(x.role)}}${x.company ? `, ${e(x.company)}` : ""} \\hfill ${e(x.period)}\n${items(x.bullets)}`)
    .join("\n")

  return `% Generated by LaunchPad. Single column, standard headings, selectable text: ATS-friendly.
% Replace any [placeholder] with a real number, or delete it. Never invent numbers.
\\documentclass[10.5pt,a4paper]{article}
\\usepackage[margin=0.7in]{geometry}
\\usepackage[T1]{fontenc}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\setlist[itemize]{leftmargin=1.2em,itemsep=1pt,topsep=2pt}
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}

\\begin{document}
{\\LARGE\\textbf{${e(doc.name)}}}\\\\[2pt]
${doc.headline ? `${e(doc.headline)}\\\\[2pt]\n` : ""}${e(doc.contact.join(" | "))}

${section("Education", education)}${section("Skills", skills)}${section("Projects", projects)}${section("Experience", experience)}\\end{document}
`
}
