import { REFUND_LINE } from "@/config/pricing"

export type FaqItem = { question: string; answer: string }

/** Plain-language answers. Keep each answer to 1–3 short sentences. */
export const FAQ: FaqItem[] = [
  {
    question: "Do you write the project for me?",
    answer:
      "No. You build it yourself with daily guidance, hints and a mentor chat, so you can defend every decision in an interview. The only thing we push to your GitHub is the starting scaffold, clearly labelled as generated by LaunchPad.",
  },
  {
    question: "Do I need to sign up to try it?",
    answer:
      "No. Upload your resume and set up your portfolio without an account. We only ask you to sign in with Google or GitHub when you publish, so your portfolio has an owner.",
  },
  {
    question: "Is my resume private?",
    answer:
      "Yes. Your resume is stored in a private bucket that only you can access, and we never log its contents. You can delete all your data with one click.",
  },
  {
    question: "What do I get for free?",
    answer:
      "A live portfolio site, your overall profile score, and one of the five diagnostic pillars explained in full, including exactly how it was scored.",
  },
  {
    question: "Is the score an official industry standard?",
    answer:
      "No, and we won't pretend it is. It's the LaunchPad Rubric: a fixed checklist of what product-company screeners look for. Every score shows which checks you met and which you didn't.",
  },
  {
    question: "How much time does the 14-day program take?",
    answer:
      "About 45–60 minutes a day. Each day has one focused task with a time estimate. Missed a day? You can catch up, and your streak shows it honestly.",
  },
  {
    question: "I don't use GitHub much. Can I still join?",
    answer:
      "Yes. You connect a free GitHub account when you start the program, and Day 1 walks you through committing and pushing your work.",
  },
  {
    question: "How do I pay, and can I get a refund?",
    answer: `One-time payments through Razorpay: UPI, cards or netbanking. No subscriptions. ${REFUND_LINE}`,
  },
]
