import type { CatalogProject } from "./types"

export const collabCodePad: CatalogProject = {
  key: "collab-code-pad",
  title: "Real-time Collaborative Code Pad",
  tagline: "Several people, one editor, no conflicts, like Google Docs for code.",
  description:
    "A shared code editor where edits sync instantly between users using a CRDT (Yjs) over WebSockets, with live cursors, presence, offline editing, saved history, and Redis pub/sub so it scales past one server.",
  difficulty: "Advanced",
  roles: ["frontend", "fullstack", "mobile"],
  stack: ["TypeScript", "React", "Next.js", "Node.js", "WebSockets", "Yjs", "Redis", "PostgreSQL"],
  skills: ["TypeScript", "React", "Next.js", "Node.js", "Redis", "PostgreSQL"],
  strengthens: ["u1", "u3", "a1", "a2", "a4", "a5", "a6", "d1", "d3", "d4"],
  interviewTopics: [
    "How do two people editing the same line not overwrite each other?",
    "What happens when a user goes offline and comes back?",
    "How do you run this on more than one server?",
    "How do you keep the UI fast with many live cursors?",
  ],
  jdMapping: [
    { company: "Postman", asks: "Real-time collaboration, WebSockets, TypeScript" },
    { company: "Zoho", asks: "Collaborative editors, frontend performance" },
    { company: "Atlassian", asks: "Real-time sync, React, scalable services" },
  ],
  architecture: {
    overview:
      "A Next.js frontend hosts a CodeMirror editor bound to a Yjs document. Clients connect to a Node WebSocket server per room; Yjs merges concurrent edits without conflicts. Awareness messages carry cursors and presence. Documents are snapshotted to Postgres, and Redis pub/sub relays updates between server instances.",
    components: [
      { name: "Editor (Next.js + CodeMirror)", role: "Local-first editing bound to a Yjs document." },
      { name: "Yjs CRDT", role: "Merges concurrent edits deterministically, even offline." },
      { name: "WebSocket server (Node)", role: "Rooms, sync protocol, awareness (cursors/presence)." },
      { name: "Redis pub/sub", role: "Fans updates out across multiple server instances." },
      { name: "PostgreSQL", role: "Periodic document snapshots and version history." },
    ],
    decisions: [
      { decision: "CRDT (Yjs) instead of operational transform", why: "No central transform server; offline edits merge automatically.", tradeoff: "Documents carry some metadata overhead." },
      { decision: "Snapshots, not every keystroke, in Postgres", why: "Keeps writes low; Yjs updates are compact and replayable.", tradeoff: "A crash can lose edits since the last snapshot unless updates are also logged." },
      { decision: "Redis pub/sub between servers", why: "Users in the same room can land on different servers.", tradeoff: "Pub/sub isn't durable; clients resync on reconnect." },
    ],
  },
  runtime: "node",
  days: [
    { day: 1, title: "Set up the web app and a WebSocket server", goal: "A Next.js page and a Node WebSocket server that echo messages between two browser tabs.", why: "Understanding raw WebSockets first makes the CRDT layer easy to explain.", minutes: 45, steps: ["Run `docker compose up -d` for Redis and Postgres.", "Start the web app and the ws server as two npm scripts.", "Broadcast any message to other clients in the same room."], hints: ["Use the `ws` package; keep rooms in a Map<roomId, Set<socket>>."], checklist: ["Two tabs exchange messages", "Rooms are isolated"], defend: ["WebSockets vs polling vs server-sent events: when would you use each?"] },
    { day: 2, title: "Add the code editor", goal: "A CodeMirror 6 editor with syntax highlighting and a room URL like /room/abc.", why: "A good editor experience is what users notice first.", minutes: 45, steps: ["Add CodeMirror with a JavaScript language mode.", "Create a room id when none is given.", "Show a 'Copy invite link' button."], hints: ["Load CodeMirror only on the client (dynamic import)."], checklist: ["Editor works with highlighting", "Room links are shareable"], defend: ["Why load the editor only on the client?"] },
    { day: 3, title: "Sync edits with Yjs", goal: "Two tabs editing the same room stay identical, even when typing on the same line.", why: "This is the heart of the project: conflict-free merging.", minutes: 60, steps: ["Create a Y.Doc per room and bind it with y-codemirror.next.", "Use y-websocket's protocol on your server (or its server utils).", "Type in both tabs at once and confirm they converge."], hints: ["Read how Yjs gives every character a unique id; that's why edits don't clash."], checklist: ["Concurrent edits converge", "No lost characters"], defend: ["How do two people editing the same line not overwrite each other?"] },
    { day: 4, title: "Live cursors and presence", goal: "See other users' names, colours and cursors in real time.", why: "Presence makes collaboration feel alive and is a common feature question.", minutes: 45, steps: ["Use the Yjs awareness protocol.", "Assign each user a name and colour.", "Show a 'who's here' list; remove users when they disconnect."], hints: ["Awareness state is ephemeral; it isn't stored in the document."], checklist: ["Cursors show with names", "Users disappear on disconnect"], defend: ["Why keep presence out of the document itself?"] },
    { day: 5, title: "Save documents to Postgres", goal: "Rooms persist: reload the page tomorrow and the code is still there.", why: "Persistence strategy is a key design decision to discuss.", minutes: 50, steps: ["Store the encoded Yjs state (Y.encodeStateAsUpdate) per room.", "Snapshot every 10 seconds of activity and on last disconnect.", "Load it when the first user joins."], hints: ["Debounce snapshots; don't write on every keystroke."], checklist: ["Content survives restarts", "Writes are debounced"], defend: ["Why snapshots instead of saving every keystroke?"] },
    { day: 6, title: "Offline editing and reconnect", goal: "Edit while offline; changes merge when the connection returns.", why: "Offline support is where CRDTs shine. You'll demo it live in interviews.", minutes: 45, steps: ["Add y-indexeddb for a local copy.", "Show connection status (online, reconnecting, offline).", "Test: go offline, edit in both tabs, reconnect."], hints: ["Use exponential backoff for reconnect attempts."], checklist: ["Offline edits survive reload", "Merge after reconnect works", "Status indicator is accurate"], defend: ["What happens when a user goes offline and comes back?"] },
    { day: 7, title: "Scale past one server with Redis pub/sub", goal: "Two server instances share rooms via Redis; users on different servers see each other's edits.", why: "Horizontal scaling of stateful connections is a senior-level topic you can own.", minutes: 55, steps: ["Run two ws servers on different ports.", "Publish Yjs updates and awareness to a Redis channel per room.", "Apply messages from other instances locally."], hints: ["Tag messages with an instance id so you don't re-apply your own."], checklist: ["Edits flow between instances", "No echo loops"], defend: ["How do you run this on more than one server?"] },
    { day: 8, title: "Auth and room permissions", goal: "Sign-in, private rooms, and view-only links.", why: "Access control is expected in any real product.", minutes: 50, steps: ["Add simple email magic link or GitHub sign-in.", "Rooms have an owner and members; share view-only or edit links.", "Verify a signed token on WebSocket connect."], hints: ["Check permissions on the server; never trust the client's role."], checklist: ["Private rooms reject outsiders", "View-only users can't edit"], defend: ["How do you authenticate a WebSocket connection?"] },
    { day: 9, title: "Version history", goal: "Save named versions and restore any earlier one.", why: "History features show you can build on your data model.", minutes: 45, steps: ["Save snapshots with timestamps and optional names.", "List versions and preview one read-only.", "Restore as a new edit (don't rewrite history)."], hints: ["Restoring should be undoable too."], checklist: ["Versions list and preview", "Restore works and is undoable"], defend: ["Why restore as a new change rather than rewinding?"] },
    { day: 10, title: "Performance with many users", goal: "Smooth editing with 20 simulated users typing.", why: "Frontend performance under load is a strong differentiator.", minutes: 50, steps: ["Write a script that simulates 20 clients typing.", "Throttle awareness updates to ~10 per second.", "Measure frame rate and message counts before/after."], hints: ["The React profiler shows what re-renders; keep the editor out of React state."], checklist: ["Simulation script committed", "Awareness throttled", "Before/after numbers recorded"], defend: ["How do you keep the UI fast with many live cursors?"] },
    { day: 11, title: "Tests", goal: "Tests that two docs converge, persistence round-trips, and permissions hold.", why: "Convergence tests prove your core claim.", minutes: 55, steps: ["Unit test: apply random concurrent edits to two Y.Docs, assert equal.", "Persistence test: save, load, compare.", "Permission test for view-only rooms."], hints: ["Seed randomness so failing tests are reproducible."], checklist: ["Convergence test passes", "Persistence and permission tests pass"], defend: ["How do you test eventual consistency?"] },
    { day: 12, title: "CI", goal: "GitHub Actions builds and tests on every push.", why: "A green badge signals reliability.", minutes: 35, steps: ["Workflow with Node setup and caching.", "Run lint, type-check and tests.", "Add the badge."], hints: ["Run the Redis-dependent tests with a service container."], checklist: ["CI green", "Badge in README"], defend: ["What does CI catch that you'd miss locally?"] },
    { day: 13, title: "Load test connections", goal: "Measured maximum concurrent connections and sync latency on your machine.", why: "Numbers make your scaling claims real.", minutes: 45, steps: ["Ramp simulated clients until latency degrades.", "Measure edit-to-remote-render latency.", "Record results with hardware details."], hints: ["Measure one server, then two with Redis."], checklist: ["README has connection and latency numbers"], defend: ["What limits connections per server?"] },
    { day: 14, title: "README, demo video and deploy", goal: "Deployed app, README with diagram and decisions, and a 60-second demo GIF.", why: "Screeners love a live demo link they can open with a friend.", minutes: 60, steps: ["Deploy web to Vercel and the ws server to Render/Railway/Fly.", "README: problem, diagram, CRDT explanation, decisions, numbers.", "Record a short GIF of two cursors editing."], hints: ["WebSocket servers need a host that supports long-lived connections."], checklist: ["Live demo link works", "README complete with GIF"], defend: ["Walk me through a keystroke from my laptop to yours."] },
  ],
  defense: [
    { id: "c1", day: 3, question: "How do two people editing the same line not overwrite each other?", keyPoints: ["CRDT with unique ids per character", "deterministic merge", "no central lock", "converges on all clients"] },
    { id: "c2", day: 6, question: "What happens when a user goes offline and comes back?", keyPoints: ["local copy in IndexedDB", "edits keep working", "sync on reconnect", "automatic merge"] },
    { id: "c3", day: 7, question: "How do you run this on more than one server?", keyPoints: ["Redis pub/sub per room", "instance id to avoid echo", "clients resync on reconnect", "stateless routing possible"] },
    { id: "c4", day: 10, question: "How do you keep the UI fast with many live cursors?", keyPoints: ["throttle awareness", "avoid React re-renders", "measured before and after", "batch updates"] },
    { id: "c5", day: 1, question: "WebSockets vs polling vs server-sent events: when would you use each?", keyPoints: ["bidirectional low latency needs WebSockets", "SSE for server push only", "polling simplest but wasteful", "chose for real-time editing"] },
    { id: "c6", day: 3, question: "Why a CRDT instead of operational transform?", keyPoints: ["no central transform server", "offline friendly", "metadata overhead", "mature library"] },
    { id: "c7", day: 5, question: "Why snapshots instead of saving every keystroke?", keyPoints: ["fewer writes", "debounced", "compact Yjs state", "risk window and mitigation"] },
    { id: "c8", day: 4, question: "Why keep presence out of the document?", keyPoints: ["ephemeral state", "no history needed", "separate awareness protocol", "smaller documents"] },
    { id: "c9", day: 8, question: "How do you authenticate a WebSocket connection?", keyPoints: ["signed token on connect", "verified on server", "room permissions server-side", "view-only enforced"] },
    { id: "c10", day: 9, question: "Why restore versions as a new change?", keyPoints: ["history stays intact", "undoable", "collaborators stay in sync", "audit trail"] },
    { id: "c11", day: 11, question: "How do you test eventual consistency?", keyPoints: ["random concurrent edits", "assert docs equal", "seeded randomness", "persistence round trip"] },
    { id: "c12", day: 13, question: "What limits connections per server?", keyPoints: ["memory per socket", "event loop CPU", "measured numbers", "scale out with Redis"] },
    { id: "c13", day: 2, question: "Why load the editor only on the client?", keyPoints: ["browser-only APIs", "smaller server bundle", "faster first paint", "hydration issues avoided"] },
    { id: "c14", day: 7, question: "What happens if Redis goes down?", keyPoints: ["cross-instance sync pauses", "same-instance users unaffected", "clients resync after recovery", "pub/sub not durable"] },
    { id: "c15", day: 14, question: "Walk me through a keystroke from my laptop to yours.", keyPoints: ["local Yjs update", "WebSocket to server", "pub/sub to other instance", "applied and rendered remotely"] },
  ],
}
