import type { CatalogProject } from "./types"

export const ragNotes: CatalogProject = {
  key: "rag-notes",
  title: "RAG Search over College Notes",
  tagline: "Ask a question, get an answer with the exact page it came from.",
  description:
    "Upload lecture notes and PDFs, then search them in plain English. Retrieval uses embeddings in PostgreSQL (pgvector) plus keyword search, and every answer cites the source pages. Includes an evaluation set, so you can prove how well it works.",
  difficulty: "Intermediate",
  roles: ["data", "backend", "fullstack"],
  stack: ["Python", "FastAPI", "PostgreSQL", "pgvector", "sentence-transformers", "Docker"],
  skills: ["Python", "FastAPI", "PostgreSQL", "SQL", "Pandas", "Docker"],
  strengthens: ["u1", "u2", "u3", "a1", "a3", "a6", "d1", "d2", "d3", "d4"],
  interviewTopics: [
    "How do you know your search results are actually good?",
    "Why chunk documents, and how did you choose the chunk size?",
    "When does keyword search beat vector search?",
    "How do you stop the system making up answers?",
  ],
  jdMapping: [
    { company: "Sarvam AI", asks: "Retrieval systems, embeddings, evaluation" },
    { company: "Postman", asks: "Python APIs, search, clean API design" },
    { company: "Unacademy", asks: "Search over learning content, Python backends" },
  ],
  architecture: {
    overview:
      "A FastAPI service ingests PDFs, splits them into overlapping chunks, and stores each chunk with its embedding in Postgres using pgvector. Queries run vector similarity and full-text search together, merge the results, and return the best chunks with page citations. An optional LLM step writes an answer only from those chunks.",
    components: [
      { name: "Ingest pipeline", role: "Extracts text per page, chunks it, embeds it, and stores it." },
      { name: "PostgreSQL + pgvector", role: "Stores chunks, embeddings (HNSW index) and a full-text index." },
      { name: "Search API (FastAPI)", role: "Hybrid retrieval with reciprocal rank fusion, plus citations." },
      { name: "Answer step (optional)", role: "Writes a short answer strictly from retrieved chunks, or returns extracts." },
      { name: "Evaluation harness", role: "Question set with expected pages; reports recall@k." },
    ],
    decisions: [
      { decision: "Local embedding model (all-MiniLM-L6-v2)", why: "Free, fast on a laptop, no API keys for users.", tradeoff: "Lower quality than large hosted models." },
      { decision: "Hybrid search", why: "Exact terms like 'Dijkstra' or course codes are matched by keywords better than vectors.", tradeoff: "Two queries plus a merge step." },
      { decision: "Answer only from retrieved chunks, with citations", why: "Reduces made-up answers and lets students verify.", tradeoff: "Sometimes says 'not found' when the model might have guessed right." },
    ],
  },
  runtime: "python",
  days: [
    { day: 1, title: "Set up FastAPI with Postgres + pgvector", goal: "A FastAPI app with /health, and Postgres with the pgvector extension, both via docker compose.", why: "A reproducible setup is the foundation, and pgvector shows you can use a real database for AI search.", minutes: 45, steps: ["`docker compose up -d` starts Postgres with pgvector.", "Create a virtualenv and install requirements.", "GET /health runs `SELECT 1` and checks the vector extension.", "Run with `uvicorn app.main:app --reload`."], hints: ["`CREATE EXTENSION IF NOT EXISTS vector;` in your first migration."], checklist: ["App and database start", "/health confirms pgvector"], defend: ["Why use Postgres for vectors instead of a separate vector database?"] },
    { day: 2, title: "Extract text from PDFs page by page", goal: "POST /documents accepts a PDF and stores its text per page.", why: "Garbage in, garbage out: extraction quality decides search quality.", minutes: 45, steps: ["Use `pypdf` to read each page's text.", "Store documents(id, title) and pages(document_id, page_number, text).", "Skip empty pages and report how many were extracted."], hints: ["Keep page numbers; they become your citations later."], checklist: ["Upload stores pages with numbers", "Empty or scanned pages are reported"], defend: ["How would you handle scanned PDFs with no text?"] },
    { day: 3, title: "Chunk pages sensibly", goal: "Pages are split into ~500-character overlapping chunks that keep their page number.", why: "Chunking is the most common RAG interview question.", minutes: 40, steps: ["Split on paragraphs, then merge to about 500 characters.", "Overlap chunks by about 80 characters.", "Store chunks(id, document_id, page_number, text)."], hints: ["Try two chunk sizes later with your evaluation set and keep the better one."], checklist: ["Chunks have page numbers", "Overlap is present"], defend: ["Why overlap chunks?", "What goes wrong with very large or very small chunks?"] },
    { day: 4, title: "Embed chunks and store vectors", goal: "Each chunk has a 384-dimension embedding in a pgvector column.", why: "Embeddings are the core idea in semantic search. You'll explain them from your own code.", minutes: 45, steps: ["Load `sentence-transformers/all-MiniLM-L6-v2` once at startup.", "Embed chunks in batches of 64.", "Store in an `embedding vector(384)` column."], hints: ["Normalise embeddings so cosine similarity equals a dot product."], checklist: ["Every chunk has an embedding", "Embedding runs in batches"], defend: ["What is an embedding, in one sentence?"] },
    { day: 5, title: "Vector search with an index", goal: "GET /search?q= returns the top 5 chunks by cosine similarity, fast.", why: "Indexing vectors (HNSW) is a scaling question interviewers love.", minutes: 45, steps: ["Embed the query and order by `embedding <=> query_vec`.", "Add an HNSW index and compare query time with and without it on 10,000 chunks.", "Return text, document, page and score."], hints: ["`CREATE INDEX ON chunks USING hnsw (embedding vector_cosine_ops);`"], checklist: ["Search returns relevant chunks with pages", "Index timing recorded"], defend: ["What does an approximate index trade away?"] },
    { day: 6, title: "Add keyword search and merge (hybrid)", goal: "Search combines full-text and vector results with reciprocal rank fusion.", why: "Knowing when vectors fail (exact terms, codes) shows real understanding.", minutes: 50, steps: ["Add a `tsvector` column and GIN index.", "Run both searches, then merge with RRF: score = Σ 1/(60 + rank).", "Compare results for 'Dijkstra' and 'shortest path' queries."], hints: ["RRF needs only ranks, not comparable scores."], checklist: ["Hybrid search works", "Exact-term queries improve"], defend: ["When does keyword search beat vector search?"] },
    { day: 7, title: "Build an evaluation set", goal: "20 questions with the page that answers each, and a script that reports recall@5.", why: "\"How do you know it works?\" Evaluation is what separates real projects from demos.", minutes: 50, steps: ["Write 20 real questions from your notes and the correct document/page.", "Script: run search, check whether the right page is in the top 5.", "Report recall@5 for vector-only vs hybrid."], hints: ["Keep questions varied: definitions, comparisons, exact terms."], checklist: ["20-question set committed", "Recall@5 reported for both modes"], defend: ["What is recall@k and why did you pick it?"] },
    { day: 8, title: "Tune chunking with your evaluation", goal: "Compare two chunk sizes and keep the one with better recall.", why: "Making decisions with data is exactly what interviewers want to hear.", minutes: 45, steps: ["Re-chunk with 300 and 800 characters.", "Re-run the evaluation for each.", "Record results in a table in the README and pick one."], hints: ["Change one thing at a time."], checklist: ["Both sizes evaluated", "Choice justified with numbers"], defend: ["How did you choose your chunk size?"] },
    { day: 9, title: "Answers with citations (and no making things up)", goal: "POST /ask returns a short answer built only from retrieved chunks, with page citations, or says it wasn't found.", why: "Hallucination control is a top concern for any AI product.", minutes: 50, steps: ["If an LLM API key is configured, prompt it to answer only from the chunks and cite pages.", "Without a key, return the top extracts as the answer.", "If the best score is below a threshold, respond 'Not found in your notes'."], hints: ["Put the rules in the system prompt and the chunks in the user message."], checklist: ["Answers cite pages", "Low-confidence questions return 'not found'", "Works without an API key"], defend: ["How do you stop the system making up answers?"] },
    { day: 10, title: "Cache repeated queries", goal: "Identical queries return cached results, with hit rate logged.", why: "Caching is a classic performance topic with measurable results.", minutes: 40, steps: ["Cache query embeddings and results in memory or Redis for 10 minutes.", "Invalidate when documents change.", "Log hit rate and response time."], hints: ["Normalise the query (lowercase, trim) before using it as a key."], checklist: ["Repeat queries are faster", "Cache clears on new documents"], defend: ["How do you invalidate this cache correctly?"] },
    { day: 11, title: "Simple upload and search page", goal: "A minimal web page to upload PDFs and search, showing citations.", why: "A usable demo makes the project real for screeners who won't run code.", minutes: 50, steps: ["Serve a simple HTML page from FastAPI (or a tiny React app).", "Show results with document, page and highlighted text.", "Handle loading and empty states."], hints: ["Keep it plain; clarity beats polish here."], checklist: ["Upload works from the page", "Results show citations"], defend: ["What would you improve for real students?"] },
    { day: 12, title: "Tests", goal: "Tests for chunking, RRF merging and the search endpoint.", why: "Tests prove the parts that are easy to get subtly wrong.", minutes: 50, steps: ["Unit-test chunk sizes and overlap.", "Unit-test RRF with a hand-made example.", "API test: ingest a small PDF, search, assert the right page."], hints: ["Use a tiny test PDF committed in tests/fixtures."], checklist: ["Chunking and RRF tested", "End-to-end search test passes"], defend: ["What's hard to test in a search system?"] },
    { day: 13, title: "CI and performance numbers", goal: "GitHub Actions runs tests and the evaluation; README has latency and recall numbers.", why: "Numbers you measured are the strongest resume bullet you can write.", minutes: 45, steps: ["CI with a pgvector service container.", "Run the evaluation in CI and print recall@5.", "Measure p95 search latency on 10,000 chunks."], hints: ["Cache the embedding model download in CI."], checklist: ["CI green", "README has recall and latency"], defend: ["Your recall is X%. What limits it?"] },
    { day: 14, title: "README, diagram and deploy", goal: "README with problem, architecture, evaluation results and a deployed demo.", why: "The README is what recruiters read. Lead with the problem and the numbers.", minutes: 60, steps: ["README: problem, diagram, decisions, evaluation table, how to run.", "Deploy on Render/Railway with a managed Postgres that supports pgvector.", "Add sample notes so visitors can try it."], hints: ["Use public, shareable notes for the demo, not copyrighted textbooks."], checklist: ["README complete", "Demo deployed or one-command local run"], defend: ["Walk me through what happens when I ask a question."] },
  ],
  defense: [
    { id: "r1", day: 7, question: "How do you know your search results are actually good?", keyPoints: ["evaluation set with expected pages", "recall@k", "compared variants", "numbers not impressions"] },
    { id: "r2", day: 3, question: "Why chunk documents, and how did you choose the size?", keyPoints: ["embeddings work best on focused text", "overlap keeps context", "tested sizes with evaluation", "trade-off precision vs context"] },
    { id: "r3", day: 6, question: "When does keyword search beat vector search?", keyPoints: ["exact terms and codes", "rare words", "hybrid with rank fusion", "measured improvement"] },
    { id: "r4", day: 9, question: "How do you stop the system making up answers?", keyPoints: ["answer only from retrieved chunks", "citations", "score threshold returns not found", "system prompt rules"] },
    { id: "r5", day: 4, question: "What is an embedding?", keyPoints: ["vector representing meaning", "similar text is close", "cosine similarity", "fixed dimensions"] },
    { id: "r6", day: 5, question: "What does an approximate vector index trade away?", keyPoints: ["speed for exactness", "HNSW graph", "may miss some neighbours", "measured with and without"] },
    { id: "r7", day: 1, question: "Why Postgres + pgvector instead of a dedicated vector database?", keyPoints: ["one database to run", "joins with metadata", "good enough scale", "fewer moving parts"] },
    { id: "r8", day: 8, question: "Tell me about a decision you made with data.", keyPoints: ["chunk size experiment", "one variable at a time", "recall numbers", "chose the winner"] },
    { id: "r9", day: 10, question: "How do you invalidate your query cache?", keyPoints: ["clear on document changes", "TTL", "normalised keys", "hit rate measured"] },
    { id: "r10", day: 2, question: "How would you handle scanned PDFs?", keyPoints: ["no text layer", "OCR", "report unreadable pages", "quality trade-off"] },
    { id: "r11", day: 6, question: "How does reciprocal rank fusion work?", keyPoints: ["uses ranks not scores", "1 over k plus rank", "sums across lists", "no score calibration needed"] },
    { id: "r12", day: 13, question: "What limits your recall?", keyPoints: ["embedding model quality", "chunking", "question phrasing", "specific failure examples"] },
    { id: "r13", day: 12, question: "What's hard to test in a search system?", keyPoints: ["relevance is fuzzy", "use fixtures with known answers", "unit-test deterministic parts", "evaluation as regression test"] },
    { id: "r14", day: 11, question: "What would you change for real students using this daily?", keyPoints: ["user feedback on results", "per-user documents and auth", "better OCR", "mobile-friendly"] },
    { id: "r15", day: 14, question: "Walk me through what happens when I ask a question.", keyPoints: ["embed query", "hybrid retrieve and merge", "threshold check", "answer with citations"] },
  ],
}
