import type { CatalogProject } from "./types"

export const webhookEngine: CatalogProject = {
  key: "webhook-engine",
  title: "Distributed Webhook Delivery Engine",
  tagline: "Reliably deliver events to other servers, even when they're down.",
  description:
    "A service that accepts events and delivers them as signed HTTP webhooks to subscriber URLs, with retries, backoff, idempotency, a dead-letter queue and delivery logs. The same problem Razorpay, Stripe and GitHub solve for their webhooks.",
  difficulty: "Intermediate",
  roles: ["backend", "fullstack", "devops"],
  stack: ["Node.js", "TypeScript", "Fastify", "PostgreSQL", "Redis", "BullMQ", "Docker"],
  skills: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "Docker", "REST"],
  strengthens: ["u1", "u3", "a1", "a2", "a3", "a5", "a6", "d1", "d3", "d4"],
  interviewTopics: [
    "What happens if the receiving server is down for 2 hours?",
    "How do you make deliveries idempotent?",
    "How do you stop one slow subscriber from delaying everyone else?",
    "How would you scale this to 10,000 events per second?",
  ],
  jdMapping: [
    { company: "Razorpay", asks: "Payments-grade reliability, webhooks, idempotency, retries" },
    { company: "Postman", asks: "API design, HTTP semantics, observability" },
    { company: "Swiggy", asks: "Async processing with queues, failure handling at scale" },
  ],
  architecture: {
    overview:
      "An API accepts events and writes them to Postgres, then enqueues one delivery job per subscribed endpoint in Redis (BullMQ). Workers POST the signed payload to each endpoint with a timeout; failures are retried with exponential backoff and moved to a dead-letter queue after the last attempt. Every attempt is logged for replay and debugging.",
    components: [
      { name: "Ingest API (Fastify)", role: "Validates events, stores them, enqueues deliveries in one transaction-safe flow." },
      { name: "PostgreSQL", role: "Source of truth for endpoints, events, deliveries and attempt logs." },
      { name: "Redis + BullMQ", role: "Durable delivery queue with delays, retries and per-endpoint concurrency." },
      { name: "Delivery workers", role: "Send HTTP requests with timeouts, sign payloads, record every attempt." },
      { name: "Dead-letter queue", role: "Holds deliveries that exhausted retries, for inspection and replay." },
    ],
    decisions: [
      { decision: "Queue per delivery, not per event", why: "One slow endpoint can't block others; retries are independent.", tradeoff: "More jobs in Redis for fan-out events." },
      { decision: "Exponential backoff with jitter", why: "Gives recovering servers breathing room and avoids thundering herds.", tradeoff: "Some deliveries arrive later than they could have." },
      { decision: "At-least-once delivery + idempotency keys", why: "Exactly-once over HTTP isn't possible; receivers can dedupe safely.", tradeoff: "Receivers must handle duplicates." },
      { decision: "HMAC-SHA256 signatures", why: "Receivers can verify the sender and that the body wasn't changed.", tradeoff: "Secret rotation needs care." },
    ],
  },
  runtime: "node",
  days: [
    {
      day: 1,
      title: "Set up the project and run Postgres + Redis locally",
      goal: "A Fastify server with a /health endpoint that checks Postgres and Redis, all started with one docker compose command.",
      why: "Interviewers ask how you'd run and debug your system locally. A one-command setup shows you think about developer experience.",
      minutes: 45,
      steps: [
        "Clone your repo and run `npm install`.",
        "Start Postgres and Redis with `docker compose up -d` (the scaffold includes the file).",
        "Implement GET /health that runs `SELECT 1` on Postgres and `PING` on Redis.",
        "Return 200 with both statuses, or 503 if either is down.",
        "Commit with a message that says what you added.",
      ],
      hints: [
        "Fastify's `app.get` handler can be async; return an object and Fastify serialises it.",
        "Use `pg`'s Pool and `ioredis`; create them once at startup, not per request.",
        "Test the 503 path by stopping Redis: `docker compose stop redis`.",
      ],
      checklist: ["`docker compose up` starts Postgres and Redis", "/health returns 200 with both up", "/health returns 503 when one is down"],
      defend: ["Why check dependencies in a health endpoint?", "What's the difference between liveness and readiness checks?"],
    },
    {
      day: 2,
      title: "Model endpoints and events, and register subscribers",
      goal: "Tables for endpoints, events and deliveries, plus POST /endpoints to register a subscriber URL with its own secret.",
      why: "Data modelling is the first thing a system-design interviewer probes. Clear tables make every later feature easier to explain.",
      minutes: 50,
      steps: [
        "Write a migration for `endpoints` (id, url, secret, event_types, active), `events` (id, type, payload jsonb, created_at) and `deliveries` (id, event_id, endpoint_id, status, attempts, next_attempt_at).",
        "Add POST /endpoints that validates the URL (https only in production) and generates a random secret.",
        "Return the secret once; store it for signing later.",
        "Add GET /endpoints to list them (without secrets).",
      ],
      hints: [
        "Use `crypto.randomBytes(32).toString('hex')` for secrets.",
        "Validate request bodies with a schema (Fastify supports JSON Schema natively).",
        "Think about which columns you'll filter by later; that's where indexes go (Day 9).",
      ],
      checklist: ["Migration creates the 3 tables", "POST /endpoints validates URLs and returns a secret", "GET /endpoints never returns secrets"],
      defend: ["Why store deliveries separately from events?", "Why return the secret only once?"],
    },
    {
      day: 3,
      title: "Ingest events and deliver them from a worker",
      goal: "POST /events stores an event and enqueues one delivery per subscribed endpoint; a BullMQ worker POSTs it with a timeout.",
      why: "This is the core async pattern (accept fast, process in the background) that every product company uses.",
      minutes: 60,
      steps: [
        "POST /events: insert the event, find active endpoints subscribed to its type, insert a `deliveries` row per endpoint.",
        "Enqueue a BullMQ job per delivery with the delivery id.",
        "Write a worker that loads the delivery, POSTs the payload with a 5-second timeout, and marks it `succeeded` on 2xx.",
        "Return 202 Accepted from POST /events immediately.",
        "Try it with a request bin (e.g. a local `npx http-echo-server`).",
      ],
      hints: [
        "Use `AbortSignal.timeout(5000)` with fetch for the timeout.",
        "Why 202 and not 200? The work isn't done yet; you've only accepted it.",
        "Put only the delivery id in the job; load fresh data in the worker.",
      ],
      checklist: ["POST /events returns 202 quickly", "Each subscribed endpoint receives the payload", "Deliveries are marked succeeded on 2xx"],
      defend: ["Why not deliver synchronously inside POST /events?", "What happens if the worker crashes mid-delivery?"],
    },
    {
      day: 4,
      title: "Retry failed deliveries with exponential backoff",
      goal: "Failed deliveries retry automatically with exponential backoff and jitter, up to a maximum number of attempts.",
      why: "\"What happens if the receiving server is down for 2 hours?\" is the most common question about this project. Today is your answer.",
      minutes: 45,
      steps: [
        "Treat non-2xx responses, timeouts and network errors as failures.",
        "Configure the job with attempts: 8 and a custom backoff: delay = base × 2^attempt + random jitter.",
        "Record every attempt (status code, error, duration) in a `delivery_attempts` table.",
        "Update the delivery's `attempts` and `next_attempt_at`.",
        "Test by pointing an endpoint at a server that returns 500, then fixing it.",
      ],
      hints: [
        "BullMQ supports `backoff: { type: 'custom' }` with a `backoffStrategy` in the worker settings.",
        "Why add jitter? Picture 1,000 deliveries all retrying at exactly the same second.",
        "With base 10s and 8 attempts, work out the total time before giving up. Does it cover a 2-hour outage?",
      ],
      checklist: ["A 500 response triggers a retry", "Delays grow exponentially with jitter", "Every attempt is logged with status and duration"],
      defend: ["Why exponential backoff instead of fixed intervals?", "What is jitter and what problem does it solve?", "How long will you keep retrying, and why?"],
    },
    {
      day: 5,
      title: "Sign every payload with HMAC",
      goal: "Each delivery carries a timestamped HMAC-SHA256 signature that receivers can verify.",
      why: "Security questions come up in every backend interview. Signed webhooks show you understand authenticity and replay attacks.",
      minutes: 40,
      steps: [
        "Compute `HMAC_SHA256(secret, timestamp + '.' + body)`.",
        "Send it in an `X-Signature` header with the timestamp in `X-Timestamp`.",
        "Write a tiny verification snippet in the README for receivers.",
        "Reject verification if the timestamp is older than 5 minutes (replay protection).",
      ],
      hints: [
        "Use `crypto.createHmac('sha256', secret)`.",
        "Compare signatures with `crypto.timingSafeEqual`, not `===`. Why?",
      ],
      checklist: ["Signature header on every delivery", "README shows how to verify", "Old timestamps are rejected in the example"],
      defend: ["Why include a timestamp in the signed string?", "Why use a timing-safe comparison?"],
    },
    {
      day: 6,
      title: "Make event ingestion idempotent",
      goal: "Clients can send an Idempotency-Key header; repeats return the original result instead of creating duplicates.",
      why: "Idempotency is a favourite topic at payments companies. You'll be able to explain it from real code.",
      minutes: 45,
      steps: [
        "Add an `idempotency_keys` table (key, request_hash, response, created_at) with a unique key.",
        "On POST /events, check the key first; if found with the same request hash, return the stored response.",
        "If the same key arrives with a different body, return 422.",
        "Expire keys after 24 hours with a cleanup job.",
      ],
      hints: [
        "Insert the key inside the same transaction that creates the event, and let the unique constraint handle races.",
        "Hash the request body so you can detect key reuse with a different payload.",
      ],
      checklist: ["Repeating a request returns the same event id", "Same key + different body returns 422", "Old keys are cleaned up"],
      defend: ["How do you handle two identical requests arriving at the same time?", "Where else in this system could duplicates happen?"],
    },
    {
      day: 7,
      title: "Add a dead-letter queue and replay",
      goal: "Deliveries that exhaust retries move to a dead-letter state, and an endpoint lets you replay them.",
      why: "Interviewers want to know what happens to data that can't be processed. \"We lose it\" is the wrong answer.",
      minutes: 45,
      steps: [
        "When the final attempt fails, mark the delivery `dead` and record why.",
        "Add GET /deliveries?status=dead to list them.",
        "Add POST /deliveries/:id/replay that resets attempts and re-enqueues.",
        "Log replays so you can tell them apart from original attempts.",
      ],
      hints: ["BullMQ emits a `failed` event with `job.attemptsMade`; compare it with `job.opts.attempts`."],
      checklist: ["Exhausted deliveries become `dead`", "Dead deliveries can be listed", "Replay re-delivers and logs it"],
      defend: ["Why not retry forever?", "Who should be alerted when the dead-letter queue grows?"],
    },
    {
      day: 8,
      title: "Stop one slow endpoint from hurting the rest",
      goal: "Per-endpoint concurrency limits, so a slow or failing subscriber can't starve deliveries to others.",
      why: "\"Noisy neighbour\" questions test whether you think about fairness and isolation.",
      minutes: 50,
      steps: [
        "Limit in-flight deliveries per endpoint (e.g. 5) using a Redis counter or BullMQ groups.",
        "When an endpoint is at its limit, delay its jobs instead of blocking workers.",
        "Add a circuit breaker: after 20 consecutive failures, pause the endpoint for 10 minutes.",
      ],
      hints: [
        "An atomic `INCR` with a TTL in Redis works as a simple semaphore; remember to `DECR` in a `finally`.",
        "A paused endpoint's jobs can be re-delayed rather than failed.",
      ],
      checklist: ["At most N concurrent deliveries per endpoint", "A consistently failing endpoint gets paused", "Other endpoints keep flowing meanwhile"],
      defend: ["What is a circuit breaker and when would you open it?", "How do you keep this fair across 10,000 endpoints?"],
    },
    {
      day: 9,
      title: "Delivery logs API with indexes and pagination",
      goal: "GET /deliveries with filters (endpoint, status, time range) that stays fast as data grows.",
      why: "Indexing and pagination are core database questions. You'll show a real before/after query time.",
      minutes: 45,
      steps: [
        "Add filters and cursor-based pagination (by created_at, id).",
        "Seed 100,000 rows with a script and time the query.",
        "Add a composite index on (endpoint_id, status, created_at) and time it again.",
        "Write both timings in your README.",
      ],
      hints: ["Use `EXPLAIN ANALYZE` to see whether Postgres used your index.", "Cursor pagination avoids the slowdown of large OFFSETs. Why?"],
      checklist: ["Filters work together", "Cursor pagination returns stable pages", "README records query time before and after the index"],
      defend: ["Why cursor pagination over OFFSET?", "How did you choose the column order in your index?"],
    },
    {
      day: 10,
      title: "Make it observable",
      goal: "Structured logs with request ids, plus a /metrics endpoint with delivery counts, failures and latency.",
      why: "\"How would you know it's broken in production?\" Observability answers that.",
      minutes: 45,
      steps: [
        "Use Fastify's built-in pino logger; add a request id and delivery id to every log line.",
        "Expose Prometheus metrics with `prom-client`: deliveries total by status, attempt latency histogram, queue depth.",
        "Never log payload contents or secrets.",
      ],
      hints: ["A histogram lets you talk about p95 latency, not just averages."],
      checklist: ["Logs are JSON with ids", "/metrics shows counts and latency", "No secrets or payloads in logs"],
      defend: ["Which three metrics would you alert on?", "Why p95 instead of average latency?"],
    },
    {
      day: 11,
      title: "Write tests for the parts that matter",
      goal: "Unit tests for backoff and signing, and an integration test that delivers an event end to end.",
      why: "Tests prove your code works and give you something concrete to discuss about quality.",
      minutes: 60,
      steps: [
        "Unit-test the backoff function (delays grow, stay within bounds).",
        "Unit-test signing and verification with a known secret.",
        "Integration test: start a local HTTP receiver, send an event, assert it arrives with a valid signature.",
        "Add `npm test` to the README.",
      ],
      hints: ["Vitest or Jest both work. Use the real Postgres and Redis from docker compose for the integration test."],
      checklist: ["Backoff and signing are unit-tested", "One end-to-end integration test passes", "`npm test` is documented"],
      defend: ["What did you choose not to test, and why?", "How do you test retry behaviour without waiting minutes?"],
    },
    {
      day: 12,
      title: "Run tests on every push with GitHub Actions",
      goal: "A CI workflow that installs, lints and tests on every push and pull request.",
      why: "CI shows you work like a professional team member. Screeners notice the green check on your repo.",
      minutes: 35,
      steps: [
        "Add `.github/workflows/ci.yml` running on push and pull_request.",
        "Use service containers for Postgres and Redis.",
        "Run lint, type-check and tests.",
        "Add the CI badge to your README.",
      ],
      hints: ["GitHub Actions `services:` gives you Postgres and Redis inside the job."],
      checklist: ["CI runs on every push", "It uses real Postgres/Redis services", "README shows the status badge"],
      defend: ["What does CI protect you from?", "What would you add next: coverage, security scans, or deploys?"],
    },
    {
      day: 13,
      title: "Measure throughput with a load test",
      goal: "A load test that measures events per second and delivery latency on your machine, with real numbers in the README.",
      why: "Real numbers make your resume bullet credible, and you'll know them when asked.",
      minutes: 50,
      steps: [
        "Use `autocannon` or k6 to send events at increasing rates.",
        "Record ingest throughput, p95 API latency and time-to-delivery.",
        "Try 1 vs 4 workers and note the difference.",
        "Write down your machine specs and the results. Don't round up.",
      ],
      hints: ["Point endpoints at a fast local receiver so you measure your system, not the receiver."],
      checklist: ["Load test script is in the repo", "README has measured throughput and latency", "You compared worker counts"],
      defend: ["Where is the bottleneck in your system?", "How would you get 10x more throughput?"],
    },
    {
      day: 14,
      title: "Write the README, draw the architecture, deploy",
      goal: "A README a recruiter can skim, an architecture diagram, and the service running somewhere public.",
      why: "This is what screeners actually look at. A clear README turns your repo into interview material.",
      minutes: 60,
      steps: [
        "README: problem, architecture diagram, key decisions and trade-offs, how to run, test results, load-test numbers.",
        "Draw the diagram (Excalidraw or Mermaid in Markdown).",
        "Deploy to Render or Railway (free tiers include Postgres and Redis) or explain how to run it with docker compose.",
        "Pin the repo on your GitHub profile.",
      ],
      hints: ["Lead with the problem and one diagram. Details go lower down."],
      checklist: ["README explains problem, design and trade-offs", "Architecture diagram included", "Deployed, or one-command local run documented"],
      defend: ["Walk me through your architecture in 2 minutes.", "What would you change if you started again?"],
    },
  ],
  defense: [
    { id: "w1", day: 4, question: "What happens if the receiving server is down for 2 hours?", keyPoints: ["retries with exponential backoff", "jitter to avoid thundering herd", "total retry window covers the outage", "dead-letter queue and replay after max attempts"] },
    { id: "w2", day: 6, question: "How do you make deliveries idempotent?", keyPoints: ["at-least-once delivery", "idempotency key or event id", "receiver dedupes", "unique constraint handles races"] },
    { id: "w3", day: 8, question: "How do you stop one slow subscriber from delaying everyone else?", keyPoints: ["per-endpoint concurrency limit", "queue per delivery not per event", "circuit breaker pauses failing endpoints", "workers never block on one endpoint"] },
    { id: "w4", day: 13, question: "How would you scale this to 10,000 events per second?", keyPoints: ["measured bottleneck first", "horizontal workers", "partition or shard queues", "batch inserts and connection pooling"] },
    { id: "w5", day: 5, question: "How can a receiver trust that a webhook really came from you?", keyPoints: ["HMAC signature with shared secret", "timestamp in signed payload", "timing-safe comparison", "reject old timestamps to stop replays"] },
    { id: "w6", day: 3, question: "Why accept events with 202 and process them later?", keyPoints: ["fast response to clients", "decouples ingestion from delivery", "absorbs traffic spikes", "retries happen in background"] },
    { id: "w7", day: 3, question: "What happens if a worker crashes halfway through a delivery?", keyPoints: ["job stays in queue or is retried", "delivery may happen twice", "receivers must be idempotent", "attempt logs show what happened"] },
    { id: "w8", day: 7, question: "What do you do with deliveries that never succeed?", keyPoints: ["dead-letter state after max attempts", "record reason", "manual or automatic replay", "alert when it grows"] },
    { id: "w9", day: 9, question: "Why did you choose cursor pagination for delivery logs?", keyPoints: ["offset gets slower on deep pages", "cursor on created_at and id is stable", "works with index", "consistent under inserts"] },
    { id: "w10", day: 9, question: "How did you decide which indexes to add?", keyPoints: ["based on real query filters", "composite index column order", "measured with EXPLAIN ANALYZE", "before and after timings"] },
    { id: "w11", day: 10, question: "How would you know this system is unhealthy in production?", keyPoints: ["metrics for failures and latency", "queue depth", "p95 not average", "alerts on dead-letter growth"] },
    { id: "w12", day: 2, question: "Why is `deliveries` a separate table from `events`?", keyPoints: ["one event fans out to many endpoints", "each delivery has its own status and retries", "independent tracking", "easier queries"] },
    { id: "w13", day: 11, question: "How do you test retry logic without waiting minutes?", keyPoints: ["unit-test the backoff function", "inject or mock time", "small delays in tests", "integration test with failing receiver"] },
    { id: "w14", day: 12, question: "What does your CI pipeline check, and why?", keyPoints: ["lint and type-check", "unit and integration tests", "real Postgres and Redis services", "runs on every push"] },
    { id: "w15", day: 14, question: "What would you change if you rebuilt this from scratch?", keyPoints: ["honest trade-off reflection", "a specific decision", "what you learned", "how it would scale differently"] },
  ],
}
