import type { CatalogProject } from "@/content/projects"

/**
 * The starter repository pushed as ONE commit labelled
 * "chore: initial scaffold generated by LaunchPad". Everything after that is the student's work.
 * Boilerplate only: a runnable server with a health check and local services, no feature code.
 */
export const SCAFFOLD_COMMIT_MESSAGE = "chore: initial scaffold generated by LaunchPad"

function readme(p: CatalogProject, run: string) {
  return `# ${p.title}

${p.tagline}

${p.description}

> Built with the **LaunchPad 14-Day Program**. The starter scaffold (first commit) was generated by LaunchPad; every commit after it is my own work.

## Run it locally

\`\`\`bash
docker compose up -d   # starts the databases
${run}
\`\`\`

Then open http://localhost:3000/health (or :8000 / :8080, see below).

## Stack

${p.stack.map((s) => `- ${s}`).join("\n")}

## Architecture

See [ARCHITECTURE.md](ARCHITECTURE.md). The 14-day plan is in [ROADMAP.md](ROADMAP.md).

## Results

_Fill this in as you go: test coverage, load-test numbers, and what you learned. Only real, measured numbers._
`
}

function architecture(p: CatalogProject) {
  return `# Architecture: ${p.title}

${p.architecture.overview}

## Components

${p.architecture.components.map((c) => `- **${c.name}**: ${c.role}`).join("\n")}

## Decisions and trade-offs

${p.architecture.decisions.map((d) => `### ${d.decision}\n- Why: ${d.why}\n- Trade-off: ${d.tradeoff}`).join("\n\n")}

## Diagram

_Add your diagram here (Excalidraw image or a Mermaid block) on Day 14._
`
}

function roadmap(p: CatalogProject) {
  return `# 14-day roadmap

Tick each day off as you finish it. Commit your own work every day.

${p.days
  .map((d) => `## Day ${d.day}: ${d.title} (~${d.minutes} min)\n\n${d.goal}\n\n${d.checklist.map((c) => `- [ ] ${c}`).join("\n")}`)
  .join("\n\n")}
`
}

const GITIGNORE_COMMON = `.env
.DS_Store
*.log
`

function nodeFiles(p: CatalogProject): Record<string, string> {
  const usesFastify = p.stack.includes("Fastify")
  const deps: Record<string, string> = usesFastify
    ? { fastify: "^5.0.0", pg: "^8.13.0", ioredis: "^5.4.0", bullmq: "^5.30.0" }
    : { express: "^5.0.0", pg: "^8.13.0", ioredis: "^5.4.0", bullmq: "^5.30.0" }
  if (p.key === "collab-code-pad") Object.assign(deps, { ws: "^8.18.0", yjs: "^13.6.0" })
  const devDeps: Record<string, string> = { typescript: "^5.6.0", tsx: "^4.19.0", "@types/node": "^22.0.0", "@types/pg": "^8.11.0", vitest: "^2.1.0" }
  if (!usesFastify) devDeps["@types/express"] = "^5.0.0"
  if (p.key === "collab-code-pad") devDeps["@types/ws"] = "^8.5.0"

  const server = usesFastify
    ? `import Fastify from "fastify"
import pg from "pg"
import Redis from "ioredis"

const app = Fastify({ logger: true })
const db = new pg.Pool({ connectionString: process.env.DATABASE_URL })
const redis = new Redis(process.env.REDIS_URL ?? "redis://localhost:6379")

app.get("/health", async (_req, reply) => {
  const checks = { postgres: "down", redis: "down" }
  try { await db.query("SELECT 1"); checks.postgres = "up" } catch {}
  try { if ((await redis.ping()) === "PONG") checks.redis = "up" } catch {}
  const ok = Object.values(checks).every((v) => v === "up")
  return reply.code(ok ? 200 : 503).send({ status: ok ? "ok" : "degraded", checks })
})

const port = Number(process.env.PORT ?? 3000)
app.listen({ port, host: "0.0.0.0" })
`
    : `import express from "express"
import pg from "pg"
import Redis from "ioredis"

const app = express()
app.use(express.json())
const db = new pg.Pool({ connectionString: process.env.DATABASE_URL })
const redis = new Redis(process.env.REDIS_URL ?? "redis://localhost:6379")

app.get("/health", async (_req, res) => {
  const checks = { postgres: "down", redis: "down" }
  try { await db.query("SELECT 1"); checks.postgres = "up" } catch {}
  try { if ((await redis.ping()) === "PONG") checks.redis = "up" } catch {}
  const ok = Object.values(checks).every((v) => v === "up")
  res.status(ok ? 200 : 503).json({ status: ok ? "ok" : "degraded", checks })
})

const port = Number(process.env.PORT ?? 3000)
app.listen(port, () => console.log(\`Listening on http://localhost:\${port}\`))
`

  return {
    "package.json": JSON.stringify(
      {
        name: p.key,
        private: true,
        type: "module",
        scripts: { dev: "tsx watch --env-file=.env src/index.ts", start: "tsx --env-file=.env src/index.ts", test: "vitest run", typecheck: "tsc --noEmit" },
        dependencies: deps,
        devDependencies: devDeps,
      },
      null,
      2
    ) + "\n",
    "tsconfig.json": JSON.stringify(
      { compilerOptions: { target: "ES2022", module: "NodeNext", moduleResolution: "NodeNext", strict: true, esModuleInterop: true, skipLibCheck: true, outDir: "dist" }, include: ["src"] },
      null,
      2
    ) + "\n",
    "src/index.ts": server,
    ".env.example": "PORT=3000\nDATABASE_URL=postgres://app:app@localhost:5432/app\nREDIS_URL=redis://localhost:6379\n",
    ".gitignore": `node_modules\ndist\n${GITIGNORE_COMMON}`,
    "docker-compose.yml": `services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
  pgdata:
`,
  }
}

function pythonFiles(): Record<string, string> {
  return {
    "requirements.txt": "fastapi==0.115.*\nuvicorn[standard]==0.32.*\npsycopg[binary]==3.2.*\npgvector==0.3.*\npypdf==5.*\nsentence-transformers==3.*\npython-multipart==0.0.*\npytest==8.*\nhttpx==0.27.*\n",
    "app/__init__.py": "",
    "app/main.py": `import os

import psycopg
from fastapi import FastAPI
from fastapi.responses import JSONResponse

app = FastAPI(title="RAG Search over College Notes")
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://app:app@localhost:5432/app")


@app.get("/health")
def health():
    checks = {"postgres": "down", "pgvector": "missing"}
    try:
        with psycopg.connect(DATABASE_URL, connect_timeout=3) as conn:
            conn.execute("SELECT 1")
            checks["postgres"] = "up"
            row = conn.execute("SELECT 1 FROM pg_extension WHERE extname = 'vector'").fetchone()
            checks["pgvector"] = "installed" if row else "missing"
    except Exception:
        pass
    ok = checks["postgres"] == "up"
    return JSONResponse({"status": "ok" if ok else "degraded", "checks": checks}, status_code=200 if ok else 503)
`,
    ".env.example": "DATABASE_URL=postgresql://app:app@localhost:5432/app\n# Optional, only for Day 9 answers:\n# ANTHROPIC_API_KEY=\n",
    ".gitignore": `.venv\n__pycache__\n*.pyc\n${GITIGNORE_COMMON}`,
    "docker-compose.yml": `services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata:
`,
  }
}

function javaFiles(): Record<string, string> {
  return {
    "pom.xml": `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.6</version>
  </parent>
  <groupId>dev.launchpad</groupId>
  <artifactId>payment-gateway</artifactId>
  <version>0.1.0</version>
  <properties><java.version>21</java.version></properties>
  <dependencies>
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency>
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-redis</artifactId></dependency>
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-actuator</artifactId></dependency>
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-validation</artifactId></dependency>
    <dependency><groupId>org.flywaydb</groupId><artifactId>flyway-core</artifactId></dependency>
    <dependency><groupId>org.flywaydb</groupId><artifactId>flyway-database-postgresql</artifactId></dependency>
    <dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId><scope>runtime</scope></dependency>
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin>
    </plugins>
  </build>
</project>
`,
    "src/main/java/dev/launchpad/payments/PaymentsApplication.java": `package dev.launchpad.payments;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PaymentsApplication {
  public static void main(String[] args) {
    SpringApplication.run(PaymentsApplication.class, args);
  }
}
`,
    "src/main/resources/application.yml": `server:
  port: 8080
spring:
  datasource:
    url: \${DATABASE_URL:jdbc:postgresql://localhost:5432/app}
    username: \${DATABASE_USER:app}
    password: \${DATABASE_PASSWORD:app}
  data:
    redis:
      url: \${REDIS_URL:redis://localhost:6379}
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
`,
    "src/main/resources/db/migration/V1__init.sql": "-- Day 2: create the payments table here.\nSELECT 1;\n",
    ".env.example": "DATABASE_URL=jdbc:postgresql://localhost:5432/app\nDATABASE_USER=app\nDATABASE_PASSWORD=app\nREDIS_URL=redis://localhost:6379\n",
    ".gitignore": `target\n.idea\n*.iml\n${GITIGNORE_COMMON}`,
    "docker-compose.yml": `services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
`,
  }
}

export function buildScaffold(p: CatalogProject): Record<string, string> {
  const run =
    p.runtime === "python"
      ? "python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt\nuvicorn app.main:app --reload   # http://localhost:8000/health"
      : p.runtime === "java"
        ? "mvn spring-boot:run   # http://localhost:8080/actuator/health"
        : "npm install\ncp .env.example .env\nnpm run dev   # http://localhost:3000/health"
  const runtimeFiles = p.runtime === "python" ? pythonFiles() : p.runtime === "java" ? javaFiles() : nodeFiles(p)
  return {
    "README.md": readme(p, run),
    "ARCHITECTURE.md": architecture(p),
    "ROADMAP.md": roadmap(p),
    ...runtimeFiles,
  }
}
