import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy",
  description: "How LaunchPad handles your resume and personal data.",
}

const POINTS: { title: string; body: string }[] = [
  {
    title: "Your resume stays private",
    body: "Resumes are stored in a private storage bucket that only your account can read. We never make them public, and we never log their contents.",
  },
  {
    title: "Nothing is uploaded before you sign in",
    body: "Before you publish, your resume is read in your browser. It's saved to our servers only when you sign in to publish your portfolio.",
  },
  {
    title: "Your portfolio is public only when you publish it",
    body: "You decide what appears on your portfolio. You can hide any section or unpublish it at any time.",
  },
  {
    title: "Delete everything with one click",
    body: "You can delete your account and all your data (resume, portfolio, reports and program progress) from your account settings. Payment records are kept without your name, because the law requires us to keep them.",
  },
  {
    title: "We never commit code for you",
    body: "If you join the 14-Day Program, we push one starter commit, clearly labelled as generated by LaunchPad. Every other commit in your repo is your own work.",
  },
]

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-12 sm:px-6 md:py-20">
      <h1 className="text-h1 font-semibold md:text-h1-lg">Privacy, in plain words</h1>
      <p className="mt-3 text-muted-foreground">
        Your resume contains personal details. Here&apos;s exactly how we treat it.
      </p>
      <ul className="mt-10 flex flex-col gap-8">
        {POINTS.map((point) => (
          <li key={point.title}>
            <h2 className="text-h3 font-semibold">{point.title}</h2>
            <p className="mt-1.5 text-muted-foreground">{point.body}</p>
          </li>
        ))}
      </ul>
    </div>
  )
}
